<a href="https://colab.research.google.com/github/Dhathri19/Fourth-Semester-Guide/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Linear Regression

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('bpp_training_data.csv')
X = dataset.iloc[:, dataset.columns != 'SalePrice'].values
y = dataset.iloc[:, 1:2].values

In [ ]:
print(X)

[[1646770 1126363    8434 ...       1      17      17]
 [1821514 1194089   10150 ...       1      31      31]
 [1505138 1473654    4139 ...       1      31      31]
 ...
 [2433168 1714162    9580 ...       3      19      78]
 [1586638 1386512   11398 ...       3      19      78]
 [2396198 1082033    2144 ...       3      19      78]]


In [ ]:
print(y)

[[ 9500.]
 [14000.]
 [50000.]
 ...
 [11500.]
 [32000.]
 [47500.]]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
X_train

array([[1398665,  149377,    7009, ...,      12,      13,     347],
       [4404003, 2295848,   19327, ...,       3,       4,      63],
       [1261839, 1238451,    6788, ...,       2,       1,      32],
       ...,
       [1463411, 1480647,    7057, ...,       2,       4,      35],
       [1370053, 1455796,    4146, ...,      10,      16,     289],
       [1519615, 1274504,    1561, ...,      10,       9,     282]])

In [ ]:
X_test

array([[1364026, 1272446,    7267, ...,       6,       5,     156],
       [1657984, 1461055,    8572, ...,      12,      11,     346],
       [1419341, 1354488,    7261, ...,       9,      16,     259],
       ...,
       [1319461, 1160720,    3538, ...,       9,       9,     253],
       [1707921, 1137273,    5158, ...,       8,      31,     244],
       [1282551, 1255839,    3170, ...,       4,      28,     119]])

In [ ]:
y_train

array([[12500.],
       [ 9000.],
       [22000.],
       ...,
       [28000.],
       [12500.],
       [19000.]])

In [ ]:
y_test

array([[17000.],
       [26000.],
       [20000.],
       ...,
       [38000.],
       [10000.],
       [13750.]])

## Training the Multiple Linear Regression model on the Training set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[27713.32 17000.  ]
 [32026.71 26000.  ]
 [29391.89 20000.  ]
 ...
 [25031.07 38000.  ]
 [ 8522.3  10000.  ]
 [22761.28 13750.  ]]


In [ ]:
y_pred

array([[27713.32],
       [32026.71],
       [29391.89],
       ...,
       [25031.07],
       [ 8522.3 ],
       [22761.28]])

In [ ]:
print(np.mean((y_pred - y_test)**2))

306907645.2900281


In [ ]:
regressor.score(X_test, y_test)

0.4190212852589459